name: Tailscale RDP
on: workflow_dispatch

jobs:
  rdp:
    runs-on: windows-latest
    steps:
      - name: Enable RDP
        run: |
          Set-ItemProperty "HKLM:\System\CurrentControlSet\Control\Terminal Server" fDenyTSConnections 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          net user runneradmin Admin12345

      - name: Install Tailscale
        run: |
          choco install tailscale -y --no-progress

      - name: Connect to Tailscale
        run: |
          & "C:\Program Files\Tailscale\tailscale.exe" up --authkey=${{ secrets.TAILSCALE_AUTHKEY }} --hostname=gh-runner

      - name: Show IP
        run: |
          & "C:\Program Files\Tailscale\tailscale.exe" ip -4

      - name: Keep Alive 6h
        run: Start-Sleep 21600
