‎name: RDP
‎on:
‎  workflow_dispatch:
‎jobs:
‎  rdp:
‎    runs-on: ubuntu-latest
‎    timeout-minutes: 300
‎    steps:
‎      - name: Install xrdp and xfce
‎        run: |
          sudo apt update
          sudo apt install -y xrdp xfce4 xfce4-terminal
          sudo systemctl enable xrdp
          echo 'runner:1234'| sudo chpasswd
      - name: Start xrdp
‎        run: sudo systemctl start xrdp
‎      - name: Create tunnel and keep alive for 5 hours
‎        run: |
 timeout 18000 bash -c 'ssh -R 3389:localhost:3389 serveo.net -o StrictHostKeyChecking=no -o ServerAliveInterval=60'
